#!/usr/bin/env bash

duti -s com.microsoft.VSCodeInsiders .c all
duti -s com.microsoft.VSCodeInsiders .cpp all
duti -s com.microsoft.VSCodeInsiders .cs all
duti -s com.microsoft.VSCodeInsiders .css all
duti -s com.microsoft.VSCodeInsiders .go all
duti -s com.microsoft.VSCodeInsiders .java all
duti -s com.microsoft.VSCodeInsiders .js all
duti -s com.microsoft.VSCodeInsiders .jsx all
duti -s com.microsoft.VSCodeInsiders .ts all
duti -s com.microsoft.VSCodeInsiders .tsx all
duti -s com.microsoft.VSCodeInsiders .sass all
duti -s com.microsoft.VSCodeInsiders .scss all
duti -s com.microsoft.VSCodeInsiders .less all
duti -s com.microsoft.VSCodeInsiders .vue all
duti -s com.microsoft.VSCodeInsiders .cfg all
duti -s com.microsoft.VSCodeInsiders .json all
duti -s com.microsoft.VSCodeInsiders .lua all
duti -s com.microsoft.VSCodeInsiders .md all
duti -s com.microsoft.VSCodeInsiders .php all
duti -s com.microsoft.VSCodeInsiders .pl all
duti -s com.microsoft.VSCodeInsiders .py all
duti -s com.microsoft.VSCodeInsiders .rb all
duti -s com.microsoft.VSCodeInsiders .rs all
duti -s com.microsoft.VSCodeInsiders .sh all
duti -s com.microsoft.VSCodeInsiders .swift all
duti -s com.microsoft.VSCodeInsiders .txt all
duti -s com.microsoft.VSCodeInsiders .conf all
duti -s com.microsoft.VSCodeInsiders .yaml all
duti -s com.microsoft.VSCodeInsiders .yml all
duti -s com.microsoft.VSCodeInsiders .toml all
